In [24]:
import numpy as np
import pandas as pd

In [25]:
df=pd.read_csv('customer.csv')

In [26]:
df.sample(5)

    age  gender   review education purchased
31   22  Female     Poor    School       Yes
17   22  Female     Poor        UG       Yes
15   75    Male     Poor        UG        No
24   16  Female  Average        PG       Yes
9    74    Male     Good        UG       Yes

In [27]:
df=df.iloc[:,2:]

In [28]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [30]:
X_train

     review education
12     Poor    School
16     Poor        UG
27     Poor        PG
13  Average    School
14     Poor        PG
25     Good    School
42     Good        PG
18     Good    School
39     Poor        PG
48     Good        UG
23     Good    School
38     Good    School
7      Poor    School
29  Average        UG
24  Average        PG
31     Poor    School
6      Good    School
8   Average        UG
20  Average    School
9      Good        UG
21  Average        PG
33     Good        PG
28     Poor    School
45     Poor        PG
47     Good        PG
26     Poor        PG
1      Poor        UG
3      Good        PG
19     Poor        PG
15     Poor        UG
22     Poor        PG
46     Poor        PG
36     Good        UG
30  Average        UG
35     Poor    School
4   Average        UG
43     Poor        PG
5   Average    School
34  Average    School
32  Average        UG

In [31]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [33]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [34]:
X_train=oe.transform(X_train)

In [35]:
X_test=oe.transform(X_test)

In [36]:
X_train

array([[0., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [1., 1.]])

In [37]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [38]:
from sklearn.preprocessing import LabelEncoder

In [39]:
le=LabelEncoder()

In [40]:
le.fit(y_train)

LabelEncoder()

In [41]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [42]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [43]:
y_train

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1])